### ISSUE TITLE
CompassPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by BorzdeG** [robfletcher/gradle-compass#36]
My project uses Java 7

**Comment by ari** [comment]
I confirm. Something is forcing Java 8.

**Comment by BorzdeG** [comment]
@ari, parameter 'oraclejdk8' in https://github.com/robfletcher/gradle-compass/blob/master/.travis.yml

**Comment by ari** [comment]
No, that's just the travis tests. The problem is that the project owner compiled the jar with Java 8 and no 'source compatibility' and then uploaded that to bintray/mvn.

Since there is nothing in the release notes, I'm guessing this wasn't intentional.

Ari


On 2/02/2015 3:54pm, Victor Alenkov wrote:
> @ari <https://github.com/ari>, parameter 'oraclejdk8' in https://github.com/robfletcher/gradle-compass/blob/master/.travis.yml
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/robfletcher/gradle-compass/issues/36#issuecomment-72406404>.
> 

-- 
-------------------------->
Aristedes Maniatis
ish
http://www.ish.com.au
Level 1, 30 Wilson Street Newtown 2042 Australia
phone +61 2 9550 5001   fax +61 2 9550 4001
GPG fingerprint CBFB 84B4 738D 4E87 5E5C  5EFA EF6A 7D2E 3E49 102A

**Comment by aalmiray** [comment]
Right, looks like explicit source/target compatibility must be put in place, like

        tasks.withType(JavaCompile) {
            sourceCompatibility = '1.7'
            targetCompatibility = '1.7'
        }

        tasks.withType(GroovyCompile) {
            sourceCompatibility = '1.7'
            targetCompatibility = '1.7'
        }

AFAIK this is the only way to force the Groovy compiler to use an specific target level.

**Comment by britter** [comment]
This has been fixed with #42

**Comment by prufrock123** [comment]
Hello, 

I am still getting the same error described above, even with the 1.7 fix.

**Comment by prufrock123** [comment]
:(
